# JavaScript library for reading EXIF image metadata.
# For more information: https://github.com/exif-js/exif-js
exif:
  enable: false
  tags:
    FocalLength: "{value}mm"
    FNumber: "f/{value}"
    ExposureTime: "{value}s"
